branches:
  except:
  - "/^wip/"
language: python
python: 3.7
install:
    - pip install flake8  # pytest  # add another testing frameworks later
    - pip install pipenv
    - pipenv install --dev
script:
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - "./tests/test.sh"
    # pytest --capture=sys  # add other tests here
